### ISSUE TITLE
Error during start

### ISSUE THREAD

**Issue by EnderVlad96** [HerryYT/PocketNodeX#5]
![image](https://user-images.githubusercontent.com/32974013/62904690-35bfb180-bd1c-11e9-82ba-287e7dd05150.png)

**Comment by Erkam246** [comment]
Same

**Comment by InspectorGadget** [comment]
Hi, this issue is sourcing from a missing Node Module. For the time being, please do `npm i atob`.

**Comment by Erkam246** [comment]
now getting this
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\NodeJS\\node.exe',
1 verbose cli   'E:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (E:\NodeJS\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at E:\NodeJS\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at E:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at E:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (E:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (E:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (E:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at E:\NodeJS\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at E:\NodeJS\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd C:\Users\Erkam\Desktop\MCBE-Server\PocketNodeX-master
6 verbose Windows_NT 10.0.18362
7 verbose argv "E:\\NodeJS\\node.exe" "E:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v10.16.1
9 verbose npm  v6.9.0
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by Erkam246** [comment]
![image](https://user-images.githubusercontent.com/16340573/62933458-7f62d780-bdc2-11e9-891a-df55551b19af.png)

**Comment by nougator** [comment]
Just do `npm i` before launching for the time and it should correct it.
